config/routes.rb
Printing::Application.routes.draw do
  resources :templates

  authenticated :user do 
    root to: 'users#index', as: 'dashboard'
    get 'settings', to: 'users#settings'
  end
  root to: 'static#index'
  get 'pricing', to: 'static#pricing'
  get 'documentation', to: 'static#documentation'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
resources :jobs

  api versions: 1, module: "api/v1" do
    resources :jobs  
    resources :addresses
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
	#Associations
	belongs_to :user
	has_many :job_addresses
	has_many :jobs, through: :job_addresses

  # Attributes
  attr_accessible :name, :address_line1, :address_line2, :address_city, :address_state, :address_zip, :address_country

end

app/models/item.rb
class Item < ActiveRecord::Base
  	#Associations
  	belongs_to :user
  	belongs_to :job
    has_one :packaging
 		has_one :setting
end

app/models/job.rb
class Job < ActiveRecord::Base
  #Associations
  belongs_to :user
  has_many :job_addresses
  has_many :recipients, class_name: 'Address', through: :job_addresses, source: :address
  accepts_nested_attributes_for :recipients, reject_if: proc { |attributes| attributes['address_line1'].blank? }
  
  has_one :item
  accepts_nested_attributes_for :item
  
  #Attributes
  attr_accessible :name, :price, :quantity, :status, :items, :to_adr, :from_adr
  attr_reader :job_id, :tracking
  
end

app/models/job_address.rb
class JobAddress < ActiveRecord::Base
	#Associations
	belongs_to :job
	belongs_to :address, :dependent => :destroy

	#Attributes
	attr_accessible :job_id, :address_id
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/packaging.rb
class Packaging < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/template.rb
class Template < ActiveRecord::Base
#Associations
belongs_to :user

#Attributes
attr_accessible :name, :url

end

app/models/type.rb
class Type < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_token

  # Attributes
  attr_accessible :email, :password, :password_confirmation, :remember_me, :token
	
	#Associations
	has_many :jobs
	has_many :items
	has_many :addresses
	has_many :templates

	#Attributes
	

	#Methods

	private
	def generate_token()
		begin
			self.token = SecureRandom.hex
		end while self.class.exists?(token: token)
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/packagings_helper.rb
module PackagingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
  <div class="section">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-4 w-clearfix subfooter-left">

          <%= link_to 'PRINTR', root_path, class: 'app-name' %>
        </div>
        <% unless user_signed_in? %>
          <div class="w-col w-col-8 w-clearfix nav-column">
            <a>
              <%= link_to 'REST API', documentation_path, class: 'nav-link' %>
            </a>
            <a>
              <%= link_to 'Pricing', pricing_path, class: 'nav-link' %>
            </a>
            <a>
              <%=link_to 'Signup', new_user_registration_path, class: 'nav-link' %>
            </a>
            <a>
              <%=link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </a>
          <% else %>
            <div class="w-col w-col-8 w-clearfix nav-column">
              <a>
                <%= link_to 'REST API', documentation_path, class: 'nav-link' %>
              </a>
              <a>
                <%=link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: 'delete' %>
              </a>
          <% end %>

        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Printing" %></title>
    <%= csrf_meta_tags %>

  	<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ["Montserrat:400,700","Bitter:400,700","Droid Serif:400,700","Open Sans:300,400,600,700,800"]
        }
      });
    </script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  	<script type="text/javascript"> function hideProgress(){ document.getElementById('loader').style.display = 'none'; } </script>
  </head>
 	<body>
 		<%= render 'layouts/navbar' %>
  	<%= yield %> 
 	 	<%= javascript_include_tag "application" %>
	</body>
</html>

app/views/templates/index.html.erb
<div class='container dashboard'>
	<div class="row">
		<div class='span10 offset1'>
			<ul class="breadcrumb">
			  <li><a href="/">Jobs</a> <span class="divider">|</span></li>
			  <li class="active">Templates</a> <span class="divider">|</span></li>
			  <li><a href="settings">Settings</a></li>
			</ul>
			<table class="table striped">
			  <thead>
			    <tr>
			      <th>Template</th>
			    </tr>
			  </thead>
			  <tbody>
			    <% @templates.each do |template| %>
			      <tr>
			        <td><%= link_to template.name, template %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
	</div>
</div>

app/views/templates/show.html.erb
<div class='container dashboard'>
	<div class="row">
		<div class='span10 offset1'>
			<ul class="breadcrumb">
			  <li><%= link_to "Jobs", root_path %> <span class="divider">|</span></li>
			  <li><%= link_to "Templates", templates_path %> <span class="divider">|</span></li>
			  <li><%= link_to "Settings", settings_path %></li>
			</ul>
			<h5 id="loader" style="position: absolute;top: 150px">Template loading. Please wait...</h1>
			<iframe width = "920" height="1000" seamless=true onload="hideProgress()" src= <%= @template.url %> ></iframe>
		</div>
	</div>
</div>